// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://fhgvfuqvpfmfrxmzcawu.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoZ3ZmdXF2cGZtZnJ4bXpjYXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwNzYyNTMsImV4cCI6MjA0ODY1MjI1M30.wwcEw1fN6ppoOq-RKBHqHbzffGkc6UPJebG1KixztHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);